# Generated by Django 3.2.8 on 2022-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testes',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
