# Generated by Django 3.2.8 on 2022-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testes_kaqui'),
    ]

    operations = [
        migrations.AddField(
            model_name='testes',
            name='alecrin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
